name: taskvision
description: TaskVision - タスク管理とタイムブロッキングを効率化するモバイルアプリ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_messaging: ^14.6.3
  
  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  
  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.4
  intl: ^0.18.0
  
  # Storage
  shared_preferences: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  uuid: ^3.0.7
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  image_picker: ^0.8.8
  
  # Auth
  local_auth: ^2.1.6
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#4F46E5"
  image: assets/icons/splash_icon.png
  android: true
  ios: true
