name: Build Chrome Extension

on:
  push:
    branches: [main]
    paths:
      - 'chrome-extension/**'
  pull_request:
    branches: [main]
    paths:
      - 'chrome-extension/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  build-extension:
    name: Build Chrome Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: chrome-extension/package-lock.json

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: cd chrome-extension && npm ci

      - name: Lint
        run: cd chrome-extension && npm run lint

      - name: Build and Package
        run: |
          cd chrome-extension
          # CI環境フラグを設定
          CI=true npm run package

      - name: Upload CRX/ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-package
          path: |
            chrome-extension/dist.crx
            chrome-extension/extension.zip
          retention-days: 7

      - name: Upload Unpacked Extension
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-unpacked
          path: chrome-extension/dist
          retention-days: 7
