name: TaskVision CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to production'
        required: true
        default: false
        type: boolean

# リポジトリ全体のワークフローに対する権限を設定
permissions:
  contents: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      web-changed: ${{ steps.filter.outputs.web }}
      extension-changed: ${{ steps.filter.outputs.extension }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'web/**'
              - '.github/workflows/main.yml'
            extension:
              - 'chrome-extension/**'
              - '.github/workflows/main.yml'

  build-web:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.web-changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: cd web && npm install

      - name: Build web app
        run: cd web && npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}

      - name: Deploy to Firebase
        if: github.event_name == 'push' || github.event.inputs.deploy == 'true'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKVISION_3F130 }}
          channelId: live
          projectId: taskvision-3f130

      - name: Upload web build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web/out
          retention-days: 7

  build-extension:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.extension-changed == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: chrome-extension/package-lock.json

      - name: Get version
        id: get_version
        run: |
          VERSION=$(node -p "require('./chrome-extension/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: cd chrome-extension && npm ci

      - name: Build and Package
        run: |
          cd chrome-extension
          CI=true npm run package
          ls -la # ファイルの存在を確認

      - name: Upload CRX/ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-package
          path: |
            chrome-extension/taskvision-chrome-extension.crx
            chrome-extension/taskvision-chrome-extension.zip
          retention-days: 7

      - name: Upload Unpacked Extension
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-unpacked
          path: chrome-extension/dist
          retention-days: 7

      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          name: TaskVision Extension v${{ steps.get_version.outputs.version }}
          artifacts: 'chrome-extension/taskvision-chrome-extension.crx,chrome-extension/taskvision-chrome-extension.zip'
          body: |
            TaskVision Chrome拡張機能の最新ビルドです。

            ## インストール方法

            1. このリリースからCRXファイルをダウンロードします
            2. Chromeで chrome://extensions を開きます
            3. CRXファイルをブラウザウィンドウにドラッグ＆ドロップします

            または開発者モードでインストールする場合は、unpacked版を使用してください。
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
