name: Mobile App CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'
  pull_request:
    branches: [main]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'
  workflow_dispatch:
    inputs:
      build_apk:
        description: 'APKをビルドして成果物として保存'
        required: true
        default: true
        type: boolean

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze project
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
      
      - name: Run tests
        run: echo "Skipping tests for now"
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
