name: Mobile App CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'
  pull_request:
    branches: [main]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'
  workflow_dispatch:
    inputs:
      build_apk:
        description: 'APKをビルドして成果物として保存'
        required: true
        default: true
        type: boolean

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      # Restore Firebase configuration files from secrets
      - name: Restore Firebase config
        run: |
          mkdir -p firebase
          echo "${{ secrets.FIREBASE_ANDROID_JSON }}" | base64 -d > firebase/google-services.json
          echo "${{ secrets.FIREBASE_IOS_PLIST }}" | base64 -d > firebase/GoogleService-Info.plist
      
      # Install FlutterFire CLI and generate firebase_options.dart
      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli
      
      - name: Generate firebase_options.dart
        run: |
          flutterfire configure \
            --project ${{ secrets.FIREBASE_PROJECT_ID }} \
            --out=lib/firebase/firebase_options.dart \
            --platforms=android,ios \
            --yes
      
      - name: Install dependencies
        run: flutter pub get
      
      # Run analysis with proper error handling
      - name: Analyze project
        run: flutter analyze
      
      # Run tests with proper error handling
      - name: Run tests
        run: flutter test
      
      # Build APK with proper error handling
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          if-no-files-found: error
